<div id="menu">
<ul class="menu">
        <li><a href="javascript:;" class="parent"><span>TransMaster</span></a>
            <div><ul>
            <li><a href="transmaster.php"><span>What is TransMaster?</span></a></li>
                <li><a href="transmaster-video.php"><span>Demo Video</span></a></li>
                <li><a href="javascript:;" class="parent"><span>Targeted Training</span></a>
                    <div><ul>
                        <li><a href="methodology.php"><span>Methodology</span></a></li>
                        <li><a href="training-in-action.php"><span>Training in Action</span></a></li>
                        <li><a href="relevance.php"><span>Relevance (ROI)</span></a></li>
                    </ul></div>
                </li>
                <li><a href="features.php"><span>Features</span></a></li>
                <li><a href="javascript:;" class="parent"><span>Training Benefits</span></a>
                	    <div><ul>
                        <li><a href="javascript:;"><span>Cost Benefits</span></a></li>
                        <li><a href="javascript:;"><span>Fuel Efficiency</span></a></li>
                        <li><a href="javascript:;"><span>Scenario Training</span></a></li>
                        <li><a href="javascript:;"><span>Safety</span></a></li>
                        <li><a href="javascript:;"><span>Risk Reduction</span></a></li>
                    </ul></div>
                </li>
                <li><a href="advantages.php"><span>Advantages</span></a></li>
                <li><a href="javascript:;" class="parent"><span>Scenarios</span></a>
                    <div><ul>
                        <li><a href="javascript:;"><span>Trucking Companies</span></a></li>
                        <li><a href="javascript:;"><span>Bus Companies</span></a></li>
                        <li><a href="javascript:;"><span>Public Services</span></a></li>
                        <li><a href="javascript:;"><span>Moving Companies</span></a></li>
                        <li><a href="javascript:;"><span>Mining</span></a></li>
                        <li><a href="javascript:;"><span>School Systems</span></a></li>
                        <li><a href="javascript:;"><span>Private Companies</span></a></li>
                    </ul></div>
                </li>
            </ul></div>
        </li>
        
          <li><a href="javascript:;" class="parent"><span>TransSim</span></a>
            <div><ul>
                <li><a href="javascript:;"><span>What is TransSim?</span></a></li>
                <li><a href="javascript:;" class="parent"><span>Targeted Training</span></a>
                    <div><ul>
                        <li><a href="methodology.php"><span>Methodology</span></a></li>
                        <li><a href="training-in-action.php"><span>Training in Action</span></a></li>
                        <li><a href="relevance.php"><span>Relevance (ROI)</span></a></li>
                    </ul></div>
                </li>
                 <li><a href="features.php"><span>Features</span></a></li>
                <li><a href="javascript:;" class="parent"><span>Training Benefits</span></a>
                	    <div><ul>
                        <li><a href="javascript:;"><span>Cost Benefits</span></a></li>
                        <li><a href="javascript:;"><span>Fuel Efficiency</span></a></li>
                        <li><a href="javascript:;"><span>Scenario Training</span></a></li>
                        <li><a href="javascript:;"><span>Safety</span></a></li>
                        <li><a href="javascript:;"><span>Risk Reduction</span></a></li>
                    </ul></div>
                </li>
                <li><a href="advantages.php"><span>Advantages</span></a></li>
                <li><a href="javascript:;" class="parent"><span>Scenarios</span></a>
                    <div><ul>
                        <li><a href="javascript:;"><span>Trucking Companies</span></a></li>
                        <li><a href="javascript:;"><span>Bus Companies</span></a></li>
                        <li><a href="javascript:;"><span>Public Services</span></a></li>
                        <li><a href="javascript:;"><span>Moving Companies</span></a></li>
                        <li><a href="javascript:;"><span>Mining</span></a></li>
                        <li><a href="javascript:;"><span>School Systems</span></a></li>
                        <li><a href="javascript:;"><span>Private Companies</span></a></li>
                    </ul></div>
                </li>
            </ul></div>
        </li>
       
        <li><a href="javascript:;" class="parent"><span>ATS Team</span></a>
        		<div><ul>
        			<li><a href="ats-team.php"><span>Meet the ATS Team</span></a></li>
        			<li><a href="roadmaster.php"><span>Career Path Training</span></a></li>
        			<li><a href="ast.php"><span>AST</a></span></li>
        			<li><a href="iti.php"><span>ITI</span></a></li>
        		</ul></div>
        </li>
        <li class="last"><a href="email-us.php"><span>Contact Us</span></a></li>
    </ul>
</div>